# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ViewController

class IdentifyHardwareInterface(object):
    NONE = 0
    Mil_1553 = 1
    IP_RRU = 2
    USB_RRU = 3

