# automatically generated by the FlatBuffers compiler, do not modify

# namespace: ViewController

import flatbuffers

class Transaction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTransaction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Transaction()
        x.Init(buf, n + offset)
        return x

    # Transaction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Transaction
    def QueryOnInterfaceType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Transaction
    def QueryOnInterface(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def TransactionStart(builder): builder.StartObject(2)
def TransactionAddQueryOnInterfaceType(builder, queryOnInterfaceType): builder.PrependUint8Slot(0, queryOnInterfaceType, 0)
def TransactionAddQueryOnInterface(builder, queryOnInterface): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(queryOnInterface), 0)
def TransactionEnd(builder): return builder.EndObject()
